# Slide1

In [1]:
import tensorflow as tf

In [4]:
a = tf.add(2, 3)
sess = tf.Session()
print (sess.run(a))
sess.close()

5


In [6]:
with tf.Session() as sess: 
    print(sess.run(a))

5


In [13]:
tf.power

AttributeError: module 'tensorflow' has no attribute 'power'

In [15]:
x = 2
y = 3
op1 = tf.add(x, y)
op2 = tf.multiply(x, y)
op3 = tf.pow(op2, op1)
with tf.Session() as sess: 
    op3 = sess.run(op3)
print(op3)

7776


In [20]:
x = 2
y = 3
add_op = tf.add(x, y)
mul_op = tf.multiply(x, y)
useless = tf.multiply(x, add_op)
pow_op = tf.pow(add_op, mul_op)
with tf.Session() as sess:
    z = sess.run(pow_op)
print(z)

15625


In [22]:
x = 2
y = 3
add_op = tf.add(x, y)
mul_op = tf.multiply(x, y)
useless = tf.multiply(x, add_op)
pow_op = tf.pow(add_op, mul_op)
with tf.Session() as sess:
    z1, not_useless = sess.run([add_op, useless])
print(z1)

5


In [26]:
a = tf.constant(2, name='a') # name is for tensorboard. 
b = tf.constant(3, name = 'b')
x = tf.add(a, b)
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(x))
    
writer.close()

5


In [31]:
a = tf.constant([2, 2], name="a")
b = tf.constant([[0, 1],[2, 3]], name="b")

x = tf.add(a, b, name="add")
y = tf.multiply(a, b, name="multiply")
#writer = tf.summary.FileWriter("./graphs", sess.graph)
with tf.Session() as sess:
    print(sess.run([x, y])) # >> 5
#writer.close()

[array([[2, 3],
       [4, 5]], dtype=int32), array([[0, 2],
       [4, 6]], dtype=int32)]


In [39]:
c = tf.zeros([3,4], tf.int32)
with tf.Session() as sess: 
    print(sess.run(c))
    print(sess.run(tf.zeros_like([2.3,3,2,4,4], dtype=None, name=None, optimize=True)))
    print(sess.run(tf.fill([2, 3], 8)))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[ 0.  0.  0.  0.  0.]
[[8 8 8]
 [8 8 8]]


In [40]:
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
# We can just use 'c.eval()' without specifying the context 'sess'
print(c.eval())
sess.close()

30.0


In [44]:
# create a placeholder of type float 32-bit, shape is a vector of 3 elements
a = tf.placeholder(tf.float32, shape=[3])
# create a constant of type float 32-bit, shape is a vector of 3 elements
b = tf.constant([5, 5, 5], tf.float32)
# use the placeholder as you would a constant or a variable
c = a + b # Short for tf.add(a, b)
with tf.Session() as sess:
# feed [1, 2, 3] to placeholder a via the dict {a: [1, 2, 3]}
# fetch value of c
    for aval in [[1,2,3], [3,4,5]]:
        print(sess.run(c, {a: aval})) # the tensor a is the key, not the string ‘a’

[ 6.  7.  8.]
[  8.   9.  10.]
